Fix more warnings (#1277)
* Fix useless scaping of regexes

Fixes the following warnings after the update to `react-scripts`:

```
./src/components/Pf/PfTitle.tsx
  Line 36:   Unnecessary escape character: \-  no-useless-escape
  Line 36:   Unnecessary escape character: \-  no-useless-escape
  Line 36:   Unnecessary escape character: \-  no-useless-escape
  Line 36:   Unnecessary escape character: \-  no-useless-escape
  Line 36:  Unnecessary escape character: \-  no-useless-escape

./src/components/BreadcrumbView/BreadcrumbView.tsx
  Line 45:   Unnecessary escape character: \-  no-useless-escape
  Line 45:   Unnecessary escape character: \-  no-useless-escape
  Line 45:   Unnecessary escape character: \-  no-useless-escape
  Line 45:   Unnecessary escape character: \-  no-useless-escape
  Line 45:  Unnecessary escape character: \-  no-useless-escape
```

* Fix lint problem

This fixes the following error from tslint:
```
ERROR: kiali-ui/src/components/CytoscapeGraph/CytoscapeContextMenu.tsx:155:7 - Multiline JSX elements must be wrapped in parentheses
```

* Fix unnecesarily computed properties for style

Fixes the following warnings:

```
./src/components/IstioActions/IstioActionsDropdown.tsx
  Line 18:  Unnecessarily computed property ['.modal-content'] found  no-useless-computed-key

./src/components/IstioWizards/MatchingRouting/Rules.tsx
  Line 31:  Unnecessarily computed property ['.list-group-item-heading'] found  no-useless-computed-key
  Line 35:  Unnecessarily computed property ['.list-view-pf-actions'] found     no-useless-computed-key

./src/components/IstioWizards/SuspendTraffic.tsx
  Line 39:  Unnecessarily computed property ['.list-view-pf-main-info'] found   no-useless-computed-key
  Line 42:  Unnecessarily computed property ['.list-group-item-heading'] found  no-useless-computed-key
  Line 46:  Unnecessarily computed property ['.list-group-item-text'] found     no-useless-computed-key

./src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
  Line 39:  Unnecessarily computed property ['.rbt-token .rbt-token-remove-button'] found  no-useless-computed-key

./src/components/IstioWizards/IstioWizard.tsx
  Line 44:  Unnecessarily computed property ['.btn'] found  no-useless-computed-key

./src/components/IstioWizards/IstioWizard.tsx
  Line 44:  Unnecessarily computed property ['.btn'] found no-useless-computed-key

./src/components/IstioWizards/IstioWizardDropdown.tsx
  Line 51:  Unnecessarily computed property ['.modal-content'] found
  no-useless-computed-key

./src/components/IstioWizards/WeightedRouting.tsx
  Line 55:  Unnecessarily computed property ['.list-view-pf-main-info']
  found   no-useless-computed-key
    Line 58:  Unnecessarily computed property
    ['.list-group-item-heading'] found  no-useless-computed-key
      Line 62:  Unnecessarily computed property
      ['.list-group-item-text'] found     no-useless-computed-key
```

* Remove unreachable code

* Remove instances of using #map and not retuning anything

* Fix multiline string

* Fix syntax for casting

* Remove redundant "lone" blocks

* Remove unused import